apache/incubator-seata-samples

nacos/pom.xml, nacos/src/main/java/com/alibaba/fescar/samples/nacos/ApplicationKeeper.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/Order.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/service/AccountService.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/service/BusinessService.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/service/OrderService.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/service/StorageService.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/service/impl/AccountServiceImpl.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/service/impl/BusinessServiceImpl.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/service/impl/OrderServiceImpl.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/service/impl/StorageServiceImpl.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/starter/DubboAccountServiceStarter.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/starter/DubboBusinessTester.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/starter/DubboOrderServiceStarter.java, nacos/src/main/java/com/alibaba/fescar/samples/nacos/starter/DubboStorageServiceStarter.java, nacos/src/main/resources/file.conf, nacos/src/main/resources/jdbc.properties, nacos/src/main/resources/registry.conf, nacos/src/main/resources/spring/dubbo-account-service.xml, nacos/src/main/resources/spring/dubbo-business.xml, nacos/src/main/resources/spring/dubbo-order-service.xml, nacos/src/main/resources/spring/dubbo-storage-service.xml, nacos/src/main/resources/sql/dubbo_biz.sql, nacos/src/main/resources/sql/undo_log.sql, pom.xml
add the sample on how fescar, nacos and dubbo are integrated
=> fix #25 add the sample on how fescar, nacos and dubbo are integrated

nacos/Readme.md, nacos/pom.xml
update fescar-dubbo-nacos readme
=> update fescar-dubbo-nacos readme

nacos/Readme.md, nacos/src/main/resources/jdbc.properties
update db info and readme link url
=> update db info and readme link url

springboot-dubbo-fescar/README.md, springboot-dubbo-fescar/samples-account/src/main/resources/application.conf, springboot-dubbo-fescar/samples-dubbo-business-call/src/main/resources/application.conf, springboot-dubbo-fescar/samples-order/src/main/resources/application.conf, springboot-dubbo-fescar/samples-storage/src/main/resources/application.conf
add application.conf and change Readme.md
=> add application.conf

springboot-dubbo-fescar/samples-account/src/main/java/com/alibaba/fescar/samples/integration/account/service/TAccountServiceImpl.java, springboot-dubbo-fescar/samples-storage/src/main/java/com/alibaba/fescar/samples/integration/storage/service/TStorageServiceImpl.java
fescar-samples 例子中正确返回添加status 200
否则一直失败回滚
=> 添加正确返回status(200)

nacos/pom.xml
Signed-off-by: jimin.jm <jimin.jm@alibaba-inc.com>
=> upgrade nacos module fescar version and add logback

nacos/src/main/resources/jdbc.properties, nacos/src/main/resources/registry.conf, tcc/transfer-tcc-sample/pom.xml, tcc/transfer-tcc-sample/src/main/java/com/alibaba/fescar/samples/tcc/transfer/action/FirstTccAction.java, tcc/transfer-tcc-sample/src/main/java/com/alibaba/fescar/samples/tcc/transfer/action/SecondTccAction.java, tcc/transfer-tcc-sample/src/main/java/com/alibaba/fescar/samples/tcc/transfer/action/impl/FirstTccActionImpl.java, tcc/transfer-tcc-sample/src/main/java/com/alibaba/fescar/samples/tcc/transfer/action/impl/SecondTccActionImpl.java, tcc/transfer-tcc-sample/src/main/java/com/alibaba/fescar/samples/tcc/transfer/activity/impl/TransferServiceImpl.java, tcc/transfer-tcc-sample/src/main/java/com/alibaba/fescar/samples/tcc/transfer/env/TransferDataPrepares.java
Signed-off-by: jimin.jm <jimin.jm@alibaba-inc.com>
=> fix fescar version and nacos module registry and config type set nacos

dubbo/src/main/resources/file.conf, dubbo/src/main/resources/registry.conf, tcc/transfer-tcc-sample/src/main/resources/file.conf, tcc/transfer-tcc-sample/src/main/resources/registry.conf
…n.conf
Signed-off-by: jimin.jm <jimin.jm@alibaba-inc.com>
=> fix #70 update fescar file.conf , registry.conf and remove application.conf

dubbo/src/main/resources/file.conf, nacos/pom.xml, nacos/src/main/resources/file.conf, nacos/src/main/resources/logback.xml, springboot-dubbo-fescar/samples-account/src/main/resources/file.conf, springboot-dubbo-fescar/samples-dubbo-business-call/src/main/resources/file.conf, springboot-dubbo-fescar/samples-order/src/main/resources/file.conf, springboot-dubbo-fescar/samples-storage/src/main/resources/file.conf, springboot/src/main/resources/file.conf, tcc/dubbo-tcc-sample/src/main/resources/file.conf, tcc/local-tcc-sample/src/main/resources/file.conf, tcc/sofarpc-tcc-sample/src/main/resources/file.conf, tcc/transfer-tcc-sample/src/main/resources/file.conf
Signed-off-by: jimin.jm <jimin.jm@alibaba-inc.com>
=> fix #72 File type configuration cluster name default and handle log conflicts

springboot-dubbo-fescar/pom.xml, springboot-dubbo-fescar/samples-account/Dockerfile, springboot-dubbo-fescar/samples-account/pom.xml, springboot-dubbo-fescar/samples-account/src/main/resources/application.properties, springboot-dubbo-fescar/samples-account/src/main/resources/file.conf, springboot-dubbo-fescar/samples-account/src/main/resources/registry.conf, springboot-dubbo-fescar/samples-dubbo-business-call/Dockerfile, springboot-dubbo-fescar/samples-dubbo-business-call/pom.xml, springboot-dubbo-fescar/samples-dubbo-business-call/src/main/resources/application.properties, springboot-dubbo-fescar/samples-dubbo-business-call/src/main/resources/file.conf, springboot-dubbo-fescar/samples-dubbo-business-call/src/main/resources/registry.conf, springboot-dubbo-fescar/samples-order/Dockerfile, springboot-dubbo-fescar/samples-order/pom.xml, springboot-dubbo-fescar/samples-order/src/main/resources/application.properties, springboot-dubbo-fescar/samples-order/src/main/resources/file.conf, springboot-dubbo-fescar/samples-order/src/main/resources/registry.conf, springboot-dubbo-fescar/samples-storage/Dockerfile, springboot-dubbo-fescar/samples-storage/pom.xml, springboot-dubbo-fescar/samples-storage/src/main/resources/application.properties, springboot-dubbo-fescar/samples-storage/src/main/resources/file.conf, springboot-dubbo-fescar/samples-storage/src/main/resources/registry.conf
update fescar version
add springboot repackage
add dockerfile
update local (127.0.0.1/localhost)  to  docker service name
=> update fescar samples for docker

springboot-dubbo-fescar/pom.xml
Seata version is too low,many people reported erros。Because the RPC protocol has changed
=> FIX: seata version is too low,many people reported erros

README.md, nacos/Readme.md, springboot/README.md, tcc/dubbo-tcc-sample/README.MD, tcc/local-tcc-sample/README.MD, tcc/sofarpc-tcc-sample/README.MD, tcc/springboot-tcc-sample/README.MD, tcc/transfer-tcc-sample/README.MD
Just update all link URLs from`fescar` to `seata` in all `README.md` files.
=> Update URLs from fescar to seata in README.md.

ha/Readme.md
Change list:
- Add  HA  sample (the seata-server use db to store logs)
- Change seata maven from seata-spring/seata-*  to seata-all
=> Add  HA  sample

dubbo/pom.xml, dubbo/src/main/resources/spring/dubbo-account-service.xml, dubbo/src/main/resources/spring/dubbo-business.xml, dubbo/src/main/resources/spring/dubbo-order-service.xml, dubbo/src/main/resources/spring/dubbo-storage-service.xml, pom.xml
Signed-off-by: hongwei yi hongweiyi@hotmail.com
=> add etcd registry support

pom.xml
add spring-boot-maven-plugin
fix #161
=> add spring-boot-maven-plugin

springboot-dubbo-seata/samples-account/src/main/java/io/seata/samples/integration/account/config/SeataAutoConfig.java, springboot-dubbo-seata/samples-business/src/main/java/io/seata/samples/integration/call/config/SeataAutoConfig.java, springboot-dubbo-seata/samples-business/src/main/java/io/seata/samples/integration/call/service/BusinessServiceImpl.java, springboot-dubbo-seata/samples-order/src/main/java/io/seata/samples/integration/order/config/SeataAutoConfig.java, springboot-dubbo-seata/samples-storage/src/main/java/io/seata/samples/integration/storage/config/SeataAutoConfig.java, springboot/src/main/java/io/seata/samples/springboot/SeataSpringbootApp.java, springboot/src/main/java/io/seata/samples/springboot/config/SeataConfiguration.java
The 'fescar' still exists in some example names and code comments, so rename it to 'seata'.
=> Rename 'fescar' to 'seata'.

pom.xml
add protobuf-java  to avoid class not found exception
=> add protobuf-java version

springboot-dubbo-seata/README.md, springboot-dubbo-seata/pom.xml
solve com.alibaba.dubbo 2.6.5 jar not included @EnableDubbo  ，so switch com.alibaba.dubbo 2.6.7；
solve can not register nacos （endpoint error 400），switch nacos0.9.0 to nacos 1.1.0；
=> upgrade dubbo 、nacos version to solve @EnableDubbo no import and nacos heart request fail

.gitignore, README.md, pom.xml, springcloud-nacos-seata/README.md, springcloud-nacos-seata/base-framework-mysql-support/README.md, springcloud-nacos-seata/base-framework-mysql-support/pom.xml, springcloud-nacos-seata/base-framework-mysql-support/src/main/java/com/work/framework/config/MyBatisConfig.java, springcloud-nacos-seata/order-service/pom.xml, springcloud-nacos-seata/order-service/src/main/java/com/work/order/OrderServiceApplication.java, springcloud-nacos-seata/order-service/src/main/java/com/work/order/controller/OrderController.java, springcloud-nacos-seata/order-service/src/main/java/com/work/order/feign/AccountFeignClient.java, springcloud-nacos-seata/order-service/src/main/java/com/work/order/feign/StorageFeignClient.java, springcloud-nacos-seata/order-service/src/main/java/com/work/order/model/Order.java, springcloud-nacos-seata/order-service/src/main/java/com/work/order/repository/OrderDAO.java, springcloud-nacos-seata/order-service/src/main/java/com/work/order/service/OrderService.java, springcloud-nacos-seata/order-service/src/main/resources/application.properties, springcloud-nacos-seata/order-service/src/main/resources/registry.conf, springcloud-nacos-seata/order-service/src/test/java/com/work/order/OrderServiceApplicationTests.java, springcloud-nacos-seata/pom.xml, springcloud-nacos-seata/storage-service/pom.xml, springcloud-nacos-seata/storage-service/src/main/java/com/work/storage/StorageServiceApplication.java, springcloud-nacos-seata/storage-service/src/main/java/com/work/storage/controller/StorageController.java, springcloud-nacos-seata/storage-service/src/main/java/com/work/storage/entity/Storage.java, springcloud-nacos-seata/storage-service/src/main/java/com/work/storage/repository/StorageDAO.java, springcloud-nacos-seata/storage-service/src/main/java/com/work/storage/service/StorageService.java, springcloud-nacos-seata/storage-service/src/main/resources/application.properties, springcloud-nacos-seata/storage-service/src/main/resources/registry.conf, springcloud-nacos-seata/storage-service/src/test/java/com/work/storage/StorageServiceApplicationTests.java
add springcloud-nacos-seata sample
=> add springcloud-nacos-seata sample

springboot-dubbo-seata/README.md, springboot-dubbo-seata/samples-account/src/main/java/io/seata/samples/integration/account/AccountExampleApplication.java, springboot-dubbo-seata/samples-account/src/main/java/io/seata/samples/integration/account/config/SeataAutoConfig.java, springboot-dubbo-seata/samples-account/src/main/java/io/seata/samples/integration/account/controller/TAccountController.java, springboot-dubbo-seata/samples-account/src/main/java/io/seata/samples/integration/account/mapper/TAccountMapper.java, springboot-dubbo-seata/samples-account/src/main/java/io/seata/samples/integration/account/service/ITAccountService.java, springboot-dubbo-seata/samples-account/src/main/java/io/seata/samples/integration/account/service/TAccountServiceImpl.java, springboot-dubbo-seata/samples-account/src/main/resources/mapper/TAccountMapper.xml
=> bugfix: fix sprintboot sample commodityCode

pom.xml, tcc/transfer-tcc-sample/README.MD, tcc/transfer-tcc-sample/src/main/resources/spring/seata-dubbo-reference.xml
pom.xml
tcc/transfer-tcc-sample/README.MD
tcc/transfer-tcc-sample/src/main/resources/spring/seata-dubbo-reference.xml
=> upgrade version & fix port conflict of qos

springcloud-eureka-feign-mybatis-seata/README.md, springcloud-eureka-feign-mybatis-seata/account-server/pom.xml, springcloud-eureka-feign-mybatis-seata/account-server/src/main/java/io/seata/sample/AccountServerApplication.java, springcloud-eureka-feign-mybatis-seata/account-server/src/main/java/io/seata/sample/feign/OrderApi.java, springcloud-eureka-feign-mybatis-seata/account-server/src/main/java/io/seata/sample/service/AccountServiceImpl.java, springcloud-eureka-feign-mybatis-seata/account-server/src/main/resources/application.yml, springcloud-eureka-feign-mybatis-seata/order-server/src/main/java/io/seata/sample/controller/OrderController.java, springcloud-eureka-feign-mybatis-seata/order-server/src/main/java/io/seata/sample/dao/OrderDao.java, springcloud-eureka-feign-mybatis-seata/order-server/src/main/java/io/seata/sample/entity/Order.java, springcloud-eureka-feign-mybatis-seata/order-server/src/main/java/io/seata/sample/service/OrderService.java, springcloud-eureka-feign-mybatis-seata/order-server/src/main/java/io/seata/sample/service/OrderServiceImpl.java, springcloud-eureka-feign-mybatis-seata/order-server/src/main/resources/application.yml, springcloud-eureka-feign-mybatis-seata/order-server/src/main/resources/mapper/OrderMapper.xml, springcloud-eureka-feign-mybatis-seata/order-server/src/main/resources/order.sql, springcloud-eureka-feign-mybatis-seata/storage-server/src/main/resources/application.yml
1.add multiple server ；
2.add cycle call test;
=> add:seata HA and cycle call test

ha/Readme.md
seata-server can't automatically detect a suitable driver class
=> Add driver-class-name on HA sample

dubbo/README.md, dubbo/src/main/java/io/seata/samples/dubbo/service/impl/BusinessServiceImpl.java, dubbo/src/main/resources/spring/dubbo-business.xml, pom.xml
seata-samples：dubbo 修复了几个小问题 
1. 连接高版本mysql报错，升级Connector/J 5.1.31->5.1.44
2. 启动DubboBusinessTester报错，增加qos.port
3. 完善了一下readme.md
=> bugfix:upgrade Connector version and fix dubbo qos

springboot-mybatis/sbm-storage-service/src/main/java/io/seata/samples/storage/persistence/StorageMapper.java, springboot-mybatis/sbm-storage-service/src/main/java/io/seata/samples/storage/service/StorageService.java, springboot-mybatis/sbm-storage-service/src/main/resources/mapper/StorageMapper.xml
Reverts seata/seata-samples#275
=> Revert "bugfix: resolve the "storage" and "order" data be inconsistent"

tcc/dubbo-tcc-sample/pom.xml, tcc/dubbo-tcc-sample/src/main/java/io/seata/samples/tcc/dubbo/starter/DubboTccTransactionStarter.java, tcc/dubbo-tcc-sample/src/main/resources/spring/seata-dubbo-provider.xml, tcc/dubbo-tcc-sample/src/main/resources/spring/seata-dubbo-reference.xml
fix issue #333 by updating dubbo version , and disable dubbo qos
=> update dubbo-tcc-sample dubbo version and disable qos

springcloud-eureka-feign-mybatis-seata/README.md
modity db server sql location, I found this problem when I used this demo.
=> modify db server sql location

tcc/dubbo-tcc-sample/README.MD
=> Fesacr -> Seata

multiple-datasource-mybatis-plus/pom.xml, multiple-datasource/pom.xml, pom.xml, saga/sofarpc-saga-sample/pom.xml, seata-spring-boot-starter-samples/pom.xml, seata-xa/pom.xml, springboot-shardingsphere-seata/pom.xml, springcloud-eureka-feign-mybatis-seata/pom.xml, springcloud-jpa-seata/pom.xml, tcc/hsf-tcc-sample/pom.xml, tcc/sofarpc-tcc-sample/pom.xml, tcc/springboot-tcc-sample/pom.xml
Signed-off-by: slievrly <slievrly@163.com>
=> upgrade seata dependency to 1.3.0

springcloud-eureka-feign-mybatis-seata/account-server/src/main/resources/application.yml, springcloud-eureka-feign-mybatis-seata/order-server/src/main/resources/application.yml, springcloud-eureka-feign-mybatis-seata/storage-server/src/main/resources/application.yml
Signed-off-by: slievrly <slievrly@163.com>
=> modify some information

springcloud-eureka-feign-mybatis-seata/order-server/src/main/resources/application.yml
=> update feign default connectTimout and readTimeout

.github/workflows/maven.yml, multiple-datasource-mybatis-plus/pom.xml, multiple-datasource/pom.xml, pom.xml, saga/sofarpc-saga-sample/pom.xml, seata-spring-boot-starter-samples/pom.xml, seata-xa/pom.xml, springcloud-eureka-feign-mybatis-seata/pom.xml, springcloud-jpa-seata/pom.xml, tcc/sofarpc-tcc-sample/pom.xml, tcc/springboot-tcc-sample/pom.xml
Signed-off-by: slievrly <slievrly@163.com>
=> upgrade seata version to 1.4.2

doc/quick-integration-with-spring-cloud.md
vgroup_mapping  change vgroupMapping
=> vgroup_mapping  change vgroupMapping

multiple-datasource/src/main/java/io/seata/samples/mutiple/datasource/config/DataSourceProxyConfig.java, multiple-datasource/src/main/java/io/seata/samples/mutiple/datasource/service/impl/OrderServiceImpl.java, multiple-datasource/src/main/java/io/seata/samples/mutiple/datasource/service/impl/PayServiceImpl.java, multiple-datasource/src/main/java/io/seata/samples/mutiple/datasource/service/impl/StorageServiceImpl.java
解决项目中 @Transactional 注解未生效的问题。
因为项目中配置了多个数据源，但是没有指定哪个数据源为默认数据源，导致自动装配 DataSourceTransactionManagerAutoConfiguration 配置类没有初始化 DataSourceTransactionManager。
将降级策略打开，在执行本地事务的时候报错会回滚。
=> bugfix:@Transactional not work

dubbo/src/main/java/io/seata/samples/dubbo/service/impl/BusinessServiceImpl.java, pom.xml
Signed-off-by: slievrly <slievrly@163.com>
=> fix bulid error

springboot-mybatis/pom.xml, springboot-mybatis/sbm-account-service/src/main/java/io/seata/samples/account/persistence/Account.java, springboot-mybatis/sbm-business-service/src/main/java/io/seata/samples/business/client/OrderClient.java, springboot-mybatis/sbm-business-service/src/main/java/io/seata/samples/business/client/StockClient.java, springboot-mybatis/sbm-common-service/pom.xml, springboot-mybatis/sbm-order-service/src/main/java/io/seata/samples/order/client/AccountClient.java, springboot-mybatis/sbm-order-service/src/main/java/io/seata/samples/order/persistence/Order.java, springboot-mybatis/sbm-stock-service/src/main/java/io/seata/samples/stock/persistence/Stock.java
Signed-off-by: slievrly <slievrly@gmail.com>
fix #463
=> remove lombok resolve compile error

README.md
=> style: README.md

seata-spring-boot-starter-samples/pom.xml
解决项目启动报错 NoClassDefFoundError ：com/alibaba/spring/context/OnceApplicationContextEventListener
=> 修复 spring-context-support 版本号依赖问题

README.md, pom.xml
=> feat: 默认注释所有maven module，优化项目首次载入时间

tcc/dubbo-tcc-sample/pom.xml, tcc/dubbo-tcc-sample/src/main/java/io/seata/samples/tcc/dubbo/starter/TccProviderStarter.java, tcc/pom.xml, tcc/transfer-tcc-sample/pom.xml, tcc/transfer-tcc-sample/src/main/java/io/seata/samples/tcc/transfer/env/TransferDataPrepares.java, tcc/transfer-tcc-sample/src/main/java/io/seata/samples/tcc/transfer/starter/TransferApplication.java, tcc/transfer-tcc-sample/src/main/resources/db-bean/from-datasource-bean.xml, tcc/transfer-tcc-sample/src/main/resources/db-bean/to-datasource-bean.xml
fix tcc dubbo sample, tcc transfer sample
=> fix tcc dubbo sample, tcc transfer sample

seata-xa/stock-xa/src/main/resources/application.properties
修改seata-xa/stock-xa/application.properties db配置
=> fix seata-xa

api/src/main/java/io/seata/samples/api/utils/DataSourceUtil.java
=> fix seata-samples-api dataSource repeat

mp-shadingsphere-druid-seata-tcc/pom.xml, nutzboot-dubbo-fescar/pom.xml, pom.xml, saga/sofarpc-saga-sample/pom.xml, seata-xa/pom.xml, springboot-mybatis/pom.xml, springboot-shardingsphere-seata/pom.xml, springcloud-eureka-seata/pom.xml, springcloud-jpa-seata/pom.xml, tcc/sofarpc-tcc-sample/pom.xml, tcc/springboot-tcc-sample/pom.xml
use https to support higher maven version
fix #627
=> chore: support higher maven version

.github/workflows/CI.yml
fix CI workflow failed
fix #630
=> optimize: fix CI workflow failed

.github/workflows/ISSUE_TEMPLATE/BUG_REPORT.md, .github/workflows/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/workflows/PULL_REQUEST_TEMPLATE.md
=> optimize: add issue and PR template

CONTRIBUTING.md, CONTRIBUTING_CN.md
=> optimize: add contrbuting_CN doc

.asf.yaml
=> optimize: format asf.yaml

.gitignore
=> feat: add gitignore ignore tmp dir

at-sample/at-api/pom.xml, at-sample/spring-dubbo-seata/pom.xml, at-sample/spring-seata/pom.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-account/pom.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-business/pom.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-order/pom.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-storage/pom.xml, saga-sample/spring-seata-saga/pom.xml, tcc-sample/spring-dubbo-seata-tcc/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-account/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-business/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-order/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-storage/pom.xml
upgrade logback to 1.2.13
fix #664
=> optimize: upgrade logback to 1.2.13

at-sample/at-api/pom.xml, at-sample/at-api/src/main/resources/jdbc.properties, at-sample/spring-dubbo-seata/pom.xml, at-sample/spring-dubbo-seata/src/main/resources/application.properties, at-sample/spring-seata/pom.xml, at-sample/spring-seata/src/main/resources/application.properties, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-account/pom.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-account/src/main/resources/application.properties, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-order/pom.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-order/src/main/resources/application.properties, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-storage/pom.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-storage/src/main/resources/application.properties, at-sample/springboot-mybatis-seata/pom.xml, at-sample/springboot-mybatis-seata/src/main/resources/application.properties, at-sample/springboot-seata/pom.xml, at-sample/springboot-seata/src/main/resources/application.properties, saga-sample/spring-dubbo-seata-saga/pom.xml, saga-sample/spring-seata-saga/pom.xml, tcc-sample/springboot-sofarpc-seata-tcc/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-account/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-account/src/main/resources/application.properties, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-business/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-business/src/main/resources/application.properties, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-order/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-order/src/main/resources/application.properties, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-storage/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-storage/src/main/resources/application.properties
upgrade mysql to 8.0.28
fix #670
=> optimize: upgrade mysql to 8.0.28

at-sample/spring-seata/src/main/java/org/apache/seata/config/DataSourceConfiguration.java, at-sample/spring-seata/src/main/java/org/apache/seata/config/SeataConfiguration.java, at-sample/spring-seata/src/main/java/org/apache/seata/service/StockService.java, at-sample/spring-seata/src/main/java/org/apache/seata/service/impl/BusinessServiceImpl.java, at-sample/spring-seata/src/main/java/org/apache/seata/service/impl/OrderServiceImpl.java, at-sample/spring-seata/src/main/java/org/apache/seata/service/impl/StockServiceImpl.java, at-sample/spring-seata/src/main/resources/all.sql
=> optimize: optimize spring-seata sample

at-sample/spring-seata/src/main/java/org/apache/seata/config/DataSourceConfiguration.java, at-sample/spring-seata/src/main/java/org/apache/seata/config/SeataConfiguration.java, at-sample/spring-seata/src/main/java/org/apache/seata/service/StockService.java, at-sample/spring-seata/src/main/java/org/apache/seata/service/impl/BusinessServiceImpl.java, at-sample/spring-seata/src/main/java/org/apache/seata/service/impl/OrderServiceImpl.java, at-sample/spring-seata/src/main/java/org/apache/seata/service/impl/StockServiceImpl.java, at-sample/spring-seata/src/main/resources/all.sql, at-sample/spring-seata/src/main/resources/logback.xml
=> optimize: add logback.xml

xa-sample/springboot-feign-seata-xa/springboot-feign-seata-business/pom.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-order/pom.xml
There are seata-spring-boot-starter rely conflicts in pom.xml in xa-sample. It makes issue as follow when using 2.1.0 server : 
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
Exception in thread "main" java.lang.NoSuchMethodError: ch.qos.logback.core.util.OptionHelper.isNotEmtpy([Ljava/lang/Object;)Z
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:100)
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:90)
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:63)
at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
at …
```
=> fix: fix seata-spring-boot-starter conflict in pom.xml

at-sample/at-api/src/main/resources/logback.xml, at-sample/dubbo-samples-seata/dubbo-samples-seata-account/src/main/resources/logback.xml, at-sample/dubbo-samples-seata/dubbo-samples-seata-business/src/main/resources/logback.xml, at-sample/dubbo-samples-seata/dubbo-samples-seata-order/src/main/resources/logback.xml, at-sample/dubbo-samples-seata/dubbo-samples-seata-stock/src/main/resources/logback.xml, at-sample/spring-dubbo-seata/src/main/resources/logback.xml, at-sample/spring-seata/src/main/resources/logback.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-account/src/main/resources/logback.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-business/src/main/resources/logback.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-order/src/main/resources/logback.xml, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-storage/src/main/resources/logback.xml, at-sample/springboot-mybatis-seata/src/main/resources/logback.xml, at-sample/springboot-seata/src/main/resources/logback.xml, saga-sample/spring-dubbo-seata-saga/src/main/resources/logback.xml, saga-sample/spring-seata-saga/src/main/resources/logback.xml, tcc-sample/spring-dubbo-seata-tcc/src/main/resources/logback.xml, tcc-sample/springboot-sofarpc-seata-tcc/src/main/resources/logback.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-account/src/main/resources/logback.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-business/src/main/resources/logback.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-order/src/main/resources/logback.xml, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-storage/src/main/resources/logback.xml
Add  logback.xml to all project to modify log level to INFO
Had verify log level of all cases are INFO by starting them.
=> feature: add logback.xml to all project

at-sample/at-api/src/main/java/org/apache/seata/api/BusinessService.java
fix: fix txServiceGroup of at-api
=> fix: fix txServiceGroup of at-api

tcc-sample/spring-dubbo-seata-tcc/src/main/java/org/apache/seata/action/TccActionOne.java, tcc-sample/spring-dubbo-seata-tcc/src/main/java/org/apache/seata/action/TccActionTwo.java, tcc-sample/spring-dubbo-seata-tcc/src/main/java/org/apache/seata/action/impl/TccActionOneImpl.java, tcc-sample/spring-dubbo-seata-tcc/src/main/java/org/apache/seata/action/impl/TccActionTwoImpl.java, tcc-sample/spring-dubbo-seata-tcc/src/main/java/org/apache/seata/stater/TccConsumerStarter.java, tcc-sample/springboot-sofarpc-seata-tcc/src/main/java/org/apache/seata/SofaRPCTccTransactionApplication.java, tcc-sample/springboot-sofarpc-seata-tcc/src/main/java/org/apache/seata/action/TccActionOne.java, tcc-sample/springboot-sofarpc-seata-tcc/src/main/java/org/apache/seata/action/TccActionTwo.java, tcc-sample/springboot-sofarpc-seata-tcc/src/main/java/org/apache/seata/action/impl/TccActionOneImpl.java, tcc-sample/springboot-sofarpc-seata-tcc/src/main/java/org/apache/seata/action/impl/TccActionTwoImpl.java
=> bugfix: tcc sample check tx status error

e2e-test/e2e-test-builder/src/main/java/org/apache/seata/config/ConfigReader.java, e2e-test/pom.xml
=> optimize: upgrade some dependencies

at-sample/at-api/src/main/resources/jdbc.properties, at-sample/dubbo-samples-seata/dubbo-samples-seata-account/src/main/resources/application.yml, at-sample/dubbo-samples-seata/dubbo-samples-seata-order/src/main/resources/application.yml, at-sample/dubbo-samples-seata/dubbo-samples-seata-stock/src/main/resources/application.yml, at-sample/spring-dubbo-seata/src/main/resources/application.properties, at-sample/spring-seata/src/main/resources/application.properties, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-account/src/main/resources/application.properties, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-order/src/main/resources/application.properties, at-sample/springboot-dubbo-seata/springboot-dubbo-seata-storage/src/main/resources/application.properties, at-sample/springboot-mybatis-seata/src/main/resources/application.properties, at-sample/springboot-seata/src/main/resources/application.properties, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-account/src/main/resources/application.properties, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-order/src/main/resources/application.properties, xa-sample/springboot-feign-seata-xa/springboot-feign-seata-storage/src/main/resources/application.properties
remove hard-coded credentials to pass security check https://github.com/apache/incubator-seata-samples/pull/692
**p.s password in e2e case will be optimized in another pr after this be merged.**
=> optimize: remove hard-coded credentials

DISCLAIMER, NOTICE
=> add DISCLAIMER and NOTICE

at-sample/dubbo-samples-seata/dubbo-samples-seata-account/src/test/java/org/apache/dubbo/samples/seata/AccountApplicationTests.java, at-sample/dubbo-samples-seata/dubbo-samples-seata-business/src/test/java/org/apache/dubbo/samples/seata/business/BusinessApplicationIT.java, at-sample/dubbo-samples-seata/dubbo-samples-seata-order/src/test/java/org/apache/dubbo/samples/seata/OrderApplicationTests.java, at-sample/dubbo-samples-seata/dubbo-samples-seata-stock/src/test/java/org/apache/dubbo/samples/seata/StockApplicationTests.java, e2e-test/README-CN.md
=>  optimize: fix ci test

.asf.yaml, .github/workflows/license-checker.yaml, .gitignore, .licenserc.yaml
add license header and dependency check
=> add license header and dependency check
